--- 
- hosts: tag_Name_redis_*:tag_Name_redis_master*:tag_Name_redis_slave*
  remote_user: ec2-user
  become: yes
  gather_facts: true

  tasks:
  
    - name: Install apache on ec2 instance
      yum: 
        name: httpd
        state: present
      
    - name: Check service
      service: 
        name: httpd
        state: started
